project_id = "vjbtvobdgrhleiozbrnw"

[api]
enabled = true
port = 54321

[db]
enabled = true
port = 54322

[functions.extract-gmail-jobs]
verify_jwt = false

[functions.generate-application-documents]
verify_jwt = true