// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjbtvobdgrhleiozbrnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqYnR2b2JkZ3JobGVpb3picm53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NDI1OTAsImV4cCI6MjA2ODAxODU5MH0.y_29-bvEdSjRRrhd6rQApLwuMsB8Vld3GIenbH_Cgi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});